name : test-app



server:
  applicationConnectors:
  - type: http
    port: 9090
    idleTimeout: 30 seconds
    acceptorThreads: 1
    selectorThreads: 2
    useServerHeader: true
    useDateHeader: true
  adminConnectors:
  - type: http
    port: 9091
    idleTimeout: 30 seconds
    acceptorThreads: 1
    selectorThreads: 2
    useServerHeader: true
    useDateHeader: true

  requestLog:
    enabled: true
    appenders:
      - type: file
        currentLogFilename: /var/log/dropwizard-test/requests.log
        archivedLogFilenamePattern: /var/log/dropwizard-test/requests-%d{yyyy-MM-dd}.log.gz
        timeZone: IST

logging:
  loggers:
    org.glassfish.jersey.filter.LoggingFilter: INFO
  level: INFO
  appenders:
    - type: file
      timeZone: IST
      logFormat: "%date %level [%thread] %logger{10} [%X{id}] %msg%n"
      queueSize: 2048
      currentLogFilename: /var/log/dropwizard-test/app.log
      archive: true
      archivedLogFilenamePattern: /var/log/dropwizard-test/app-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 10
